import { readFileSync } from 'node:fs';

const source = [
  '../src/main.tsx',
  '../src/shared/model.ts',
  '../src/shared/persistence.ts',
  '../src/features/terminal/mountTerminal.ts',
  '../src/features/terminal/themes.ts',
  '../src/features/navigation/SidebarNavigation.tsx',
  '../src/features/settings/SettingsPage.tsx',
  '../src/features/session-catalog/SessionList.tsx',
  '../src/features/session-catalog/SessionDialog.tsx',
  '../src/shared/ui/ConfirmDialog.tsx',
  '../src/shared/ui/Popup.tsx',
  '../src/shared/ui/ThemeControls.tsx',
  '../src/shared/ui/ProfileFilePicker.tsx',
  '../public/sw.js',
].map(path => readFileSync(new URL(path, import.meta.url), 'utf8')).join('\n');
const themeControls = readFileSync(new URL('../src/shared/ui/ThemeControls.tsx', import.meta.url), 'utf8');
const css = readFileSync(new URL('../src/layout.css', import.meta.url), 'utf8');
const theme = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');
const allCSS = `${theme}\n${css}`;
const checks = [
  ['expanded state is not persisted', !source.includes('jian.nav_expanded')],
  ['Navigation Menu owns sidebar disclosure', source.includes('NavigationMenu.Root') && source.includes('NavigationMenu.Sub') && source.includes('orientation="vertical"')],
  ['primary navigation sections share one component', source.includes('function PrimaryNavigationItem') && (source.match(/<PrimaryNavigationItem/g) || []).length === 4],
  ['all navigation levels share one trigger component', source.includes('function MenuTrigger') && source.includes('<MenuTrigger icon={icon}>') && source.includes('<MenuTrigger variant="profile"')],
  ['Radix focus proxy cannot displace primary actions', source.includes('className="navigation-trigger-slot"') && theme.includes('.navigation-menu-row > .navigation-trigger-slot')],
  ['primary navigation row keeps a fixed height when children expand', theme.includes('.navigation-menu-row {') && theme.includes('height: 42px') && theme.includes('min-height: 42px')],
  ['navigation children are constrained by parent width', theme.includes('.navigation-menu > div,') && theme.includes('max-width: 100%') && theme.includes('overflow-x: hidden')],
  ['navigation reserves scrollbar width', theme.includes('.navigation-menu {') && theme.includes('scrollbar-gutter: stable')],
  ['refresh button spins while loading', source.includes('data-refreshing={refreshingKind || undefined}') && theme.includes('navigation-refresh-spin')],
  ['navigation labels truncate within parent width', theme.includes('text-overflow: ellipsis') && theme.includes('.secondary-navigation-label strong') && theme.includes('.session-copy') && !theme.includes('max-width: 190px')],
  ['Codex sessions are grouped by workspace in the frontend', source.includes('const codexWorkspaces = Array.from') && source.includes('按工作目录') && source.includes('workspace-navigation')],
  ['Local profile settings keep bashrc fixed and allow additions', source.includes("local_profiles: value.settings.local_profiles?.length ? value.settings.local_profiles : ['~/.bashrc']") && source.includes('addLocalProfile') && source.includes('index === 0')],
  ['launch argument rows receive focus after being added', source.includes('launchArgumentRefs') && source.includes('requestAnimationFrame(() => launchArgumentRefs.current[index]?.focus())') && source.includes('aria-label="添加启动参数"') && source.includes('>+</button>')],
  ['terminal does not steal focus from open dialogs or theme controls', source.includes("document.querySelector('[role=\"dialog\"][aria-modal=\"true\"], [role=\"dialog\"][data-state=\"open\"]')") && source.includes('if (document.querySelector') && source.includes("if (message.type === 'session.started')") && source.includes("onProgress('已连接'); focus();")],
  ['service worker refreshes deployed frontend assets', source.includes("updateViaCache: 'none'") && source.includes('registration.update()') && source.includes('jian-shell-v4') && source.includes('event.respondWith(fetch(request)')],
  ['Navigation Menu does not open on hover', source.includes('onPointerMove={preventHoverOpen}') && source.includes('event.preventDefault()')],
  ['first-level menu toggles on click', source.includes('setValue(next as Area | \'\')') && source.includes('onValueChange={selectArea}')],
  ['second-level menu toggles on click', source.includes('const toggleProfile = (next: string)') && source.includes("const toggledValue = next === profileValue ? '' : next;") && source.includes('event.preventDefault(); toggleProfile(item);') && source.includes('value={profileValue}')],
  ['open menus do not dismiss on pointer or focus exit', source.includes('onFocusOutside={event => event.preventDefault()}') && source.includes('onPointerDownOutside={event => event.preventDefault()}') && source.includes('onPointerLeave={event => event.preventDefault()}')],
  ['manual sidebar disclosure state is removed', !source.includes('openAgents') && !source.includes('openProfiles') && !source.includes('openLocal')],
  ['local and agent highlights use one active area', source.includes('useEffect(() => setValue(currentKind), [currentKind])') && source.includes("selected={currentKind === 'local'}") && source.includes("selected={currentKind === 'codex'}") && source.includes("selected={currentKind === 'hermes'}")],
  ['navigation scroll is persisted', source.includes('jian.nav_scroll_')],
  ['sidebar width is fixed by layout', css.includes('grid-template-columns: minmax(260px, 310px) minmax(0, 1fr)') && !css.includes('cursor: col-resize')],
  ['closed mobile sidebar is off-canvas', css.includes('transform: translateX(-105%)')],
  ['mobile content uses the full viewport', css.includes('.conversation {\n    width: 100%')],
  ['terminal stacks without overlaying output', theme.includes('.terminal-stage') && theme.includes('flex-direction: column') && !theme.includes('.terminal-controls {\n  position: absolute')],
  ['xterm internal surfaces follow the active terminal background', allCSS.includes('.terminal .xterm-viewport,\n.terminal .composition-view') && allCSS.includes('background-color: var(--terminal-bg)')],
  ['theme selection is persisted', source.includes("themeKey = 'jian.theme'") && source.includes('localStorage.setItem(themeKey, theme)')],
  ['interface and Terminal theme types are separate', source.includes("type Theme = 'console' | 'light' | 'black'") && source.includes("type TerminalTheme = typeof terminalThemeRegistry[number]['id']")],
  ['light and black themes have distinct non-green accents', /data-theme="light"[\s\S]*?--signal: #2563eb;[\s\S]*?\}/.test(theme) && /data-theme="black"[\s\S]*?--signal: #ffffff;[\s\S]*?\}/.test(theme)],
  ['theme names match the visible theme choices', source.includes("label: '默认主题'") && source.includes("label: '浅色主题'") && source.includes("label: 'Atom One Dark'") && source.includes("label: 'Atom One Light'")],
  ['theme control is in the top context bar', source.includes('context-actions') && source.includes('<ThemeControls interfaceTheme={theme}')],
  ['homepage exposes Terminal palette beside interface theme', source.includes('SquareTerminal') && source.includes('Terminal 配色') && source.includes('terminalThemeKey')],
  ['terminal updates from the selected theme without reconnecting', source.includes('terminalThemeColors[terminalTheme]') && source.includes('theme: terminalTheme') && source.includes('termRef.current.options.theme = terminalThemes[terminalTheme]') && source.includes('}, [terminalTheme])') && !source.includes('}, [session.id, terminalPath, terminalTheme])')],
  ['Terminal options come from one registry', source.includes('terminalThemeRegistry') && source.includes('terminalThemeOptions') && source.includes('terminalThemes') && (source.match(/id: 'atom-one-/g) || []).length === 2],
  ['theme popovers share one Radix lifecycle owner', (themeControls.match(/<Popover\.Root/g) || []).length === 1 && themeControls.includes('<Popover.Anchor virtualRef={anchor}') && themeControls.includes("target.closest('.theme-toggle')") && !source.includes('jian-terminal-theme-selected') && !source.includes("new Event('jian-terminal-theme')")],
  ['interface and terminal themes persist independently', source.includes("interfaceThemeKey = 'jian.interface_theme'") && source.includes("terminalThemeKey = 'jian.terminal_theme'") && source.includes('setTerminalTheme')],
  ['themed scrollbars are applied', css.includes('scrollbar-color: var(--scroll-thumb) var(--scroll-track)')],
  ['empty titles have a visible fallback', source.includes("|| '无标题'")],
  ['channel labels are localized', source.includes("weixin: '微信'") && source.includes("dingtalk: '钉钉'")],
  ['mobile terminal controls stay touch friendly', source.includes('<Collapsible.Content forceMount') && theme.includes('height: 42px') && theme.includes('grid-template-columns: repeat(3, minmax(0, 1fr))')],
  ['mobile terminal supports vertical touch scrolling', source.includes("addEventListener('touchmove'") && source.includes('term.scrollLines(lines)') && theme.includes('.terminal {\n    touch-action: none;')],
  ['touch terminals use a dedicated IME input buffer', source.includes('attachTerminalInputBuffer') && source.includes('terminal-input-buffer') && source.includes('inputMode="text"') && theme.includes('.terminal-input-buffer')],
  ['IME preview follows the terminal theme', source.includes('terminal-input-preview') && theme.includes('color: var(--terminal-fg)') && theme.includes('background: var(--terminal-bg)')],
  ['touch terminal focus does not return to xterm textarea', source.includes('inputBufferRef.current.focus') && source.includes("xtermTextarea.inputMode = touchInput ? 'none' : 'text'") && !source.includes('termRef.current?.focus(); } };')],
  ['touch input exclusively owns terminal focus', source.includes('xtermTextarea.disabled = touchInput')],
  ['mobile controls follow the visual keyboard viewport', source.includes('--mobile-viewport-height') && source.includes("viewport?.addEventListener('scroll'") && allCSS.includes('height: var(--mobile-viewport-height, 100dvh)')],
  ['empty state has a direct create action', source.includes('选择目录并新建会话') && source.includes('openWorkspace(kind, profile)')],
  ['keyboard focus is visible', allCSS.includes(':focus-visible')],
  ['reduced motion is respected', theme.includes('prefers-reduced-motion: reduce')],
  ['raw native IDs are not in the visible session heading', !source.includes('displayDetailTitle')],
  ['mobile navigation uses one drawer state', source.includes('mobileNavigationOpen') && source.includes('nav-mobile-open')],
  ['terminal status opens a menu with reconnect action', source.includes('terminal-status-menu') && source.includes('重新连接') && source.includes('setTerminalRevision')],
  ['terminal manager uses one active pool', source.includes("type TerminalStatusResponse = { active_pool: TerminalStatus[] }") && !source.includes('inactive_pool')],
  ['terminal session count opens the release-all menu', source.includes('terminal-pool-count') && source.includes('onReleaseAll') && source.includes('terminal-release-all-action') && !source.includes('release-all-button')],
  ['portaled confirmation dialogs render above their overlay', theme.includes('.dialog-overlay {') && theme.includes('z-index: 30') && /\.dialog\s*\{[\s\S]*?position: fixed;[\s\S]*?z-index: 31;/.test(theme) && /\.dialog\s*\{[\s\S]*?height: auto;[\s\S]*?max-height: calc\(100dvh - 40px\);/.test(theme) && source.includes('Dialog.Portal')],
  ['theme popover uses Radix portal positioning without legacy offsets', themeControls.includes('<Popover.Portal>') && themeControls.includes('<Popover.Content') && /\.theme-menu\s*\{[\s\S]*?\}/.test(theme) && !/\.theme-menu\s*\{[^}]*position:\s*absolute/.test(theme) && !/\.theme-menu\s*\{[^}]*top:/.test(theme) && !/\.theme-menu\s*\{[^}]*right:/.test(theme)],
  ['workspace picker keeps the launch action visible', theme.includes('.directory-list {') && theme.includes('min-height: 0;') && theme.includes('.workspace-picker > footer') && theme.includes('flex-wrap: wrap;')],
  ['agent roster disclosure is owned only by the Radix trigger button', source.includes('<Accordion.Item className="agent-roster-item" value={kind}>') && source.includes('<Accordion.Trigger className="agent-roster-trigger"') && !source.includes('toggleFromItem') && !source.includes('onClickCapture') && !source.includes('toggleExpanded') && !source.includes('agent-roster-item" value={kind} onClick')],
  ['agent roster has no custom item hover behavior', !theme.includes('.agent-roster-item:hover') && !theme.includes('.agent-roster-item:has(.agent-switch:hover') && !theme.includes('.agent-roster-item:has(.agent-roster-content') && !source.includes('agent-roster-item:hover')],
  ['agent roster h3 and trigger exactly fill the row', theme.includes('.agent-toggle-row { position: relative; display: flex; width: 100%; height: 58px') && theme.includes('.agent-toggle-row > h3 { width: 100%; height: 100%') && theme.includes('margin: 0; padding: 0; box-sizing: border-box;') && theme.includes('.agent-roster-trigger { display: flex; width: 100%; height: 100%; box-sizing: border-box;')],
  ['Local roster switch is always active and disabled', source.includes('disabled={kind === \'local\'}') && source.includes('checked={enabled}') && source.includes("kind === 'local' ? undefined : toggle") && theme.includes('.agent-switch:disabled')],
  ['profile file picker has one shared Radix implementation', (source.match(/function ProfileFilePicker/g) || []).length === 1 && source.includes("from './shared/ui/ProfileFilePicker'") && source.includes("from '../../shared/ui/ProfileFilePicker'") && source.includes('<Dialog.Portal>')],
  ['new agent sessions invalidate older list loads', source.includes('invalidateSessionLoads(token.current)') && source.includes('isCurrentSessionLoad(token.current, t)')],
  ['Local opens a homepage without starting Bash', source.includes("'LOCAL · HOME'") && source.includes('这里不会自动打开 Bash') && !source.includes('localAutoInitialized') && !source.includes('const saved = restoreLocalSession')],
];

const failed = checks.filter(([, passed]) => !passed);
for (const [name, passed] of checks) console.log(`${passed ? 'PASS' : 'FAIL'} ${name}`);
if (failed.length) process.exit(1);
